---
- name: update web servers
  hosts: web

  tasks:
  - name: ensure directory is created
    file:
      path: /home/centos/web
      state: directory

- name: update app servers
  hosts: app

  tasks:
  - name: ensure directory is created
    file:
      path: /home/centos/app
      state: directory

...
