---
- name: update web servers
  hosts: app
  become: yes

  tasks:
  - name: ensure port is changed
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf

  - name: ensure SELinux is permisive
    selinux:
      policy: targeted
      state: permissive

  - name: ensure apache is restarted
    service:
      name: httpd
      state: restarted
...
