---
- name: update web servers
  hosts: ubuntu
  become: yes

  tasks:
  - name: ensure apache is installed
    package:
      name: apache2
      state: present

  - name: ensure apache is enabled
    service:
      name: apache2
      enabled: yes

  - name: ensure apache is started
    service:
      name: apache2
      state: started

...
