---
- name: update web servers
  hosts: all
  become: yes

  tasks:
  - name: ensure apache is installed
    package:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: ensure apache is installed
    package:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: ensure apache is enabled
    service:
      name: apache2
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: ensure apache is enabled
    service:
      name: httpd
      enabled: yes
    when: ansible_os_family == "RedHat"
  
  - name: ensure apache is started
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: ensure apache is started
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
...


